### ISSUE TITLE
TAU related examples are out of date

### ISSUE THREAD

**Issue by lslachciak** [Samsung/WATT#150]
All TAU related samples are out of date.
They contains old verison of TAU.

Update all TAU relatedsamples to latest version basing on TAU 1.1

**Comment by pkaczmarczy** [comment]
I am preparing a path for this issue.

I will remove current TAU samples and replace it with new one:
For mobile I will add:
 TAU Base and UIComponents app with TAU 1.1
For wearable:
 TAU Base and UIComponents app with TAU 1.1

**Comment by pkaczmarczy** [comment]
PR has been already merged.
