### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by hsiwkin** [Samsung/WATT#172]
# Description
Can't create new project in WATT

# Steps to reproduce
* Click New Project
* Choose options in wizard: `Web Application (HTML/JS) -> Sample -> Wearable -> TAU BASE`
* Add Project Name

# Expected behaviour
The new project is created.

# Actual behaviour
Popup with error (`{"errno":-2,"code":"ENOENT","syscall":"lstat","path":"TAU/1.1/dist"}`) appears.

**Comment by grzegorz-czajkowski** [comment]
Can't reproduce this.
It looks like TAU submodule is not present. Did you run ./launch -bp ? If yes, that is the cause.
Please re-check this by running watt as:
`./launch`

**Comment by hsiwkin** [comment]
You're right - I've launched it with `./launch -bp`. 
After updating submodules it works fine.
