### ISSUE TITLE
Adjust WATT to TAU without dist folder

### ISSUE THREAD

**Issue by lslachciak** [Samsung/WATT#216]
In TAU dist folder was removed.

Adjust WATT to the situation especially for:
- serving examples
- creating new sample projects

**Comment by grzegorz-czajkowski** [comment]
Added code which installs node in version specified in .nvmrc using nvm. There is a need to:
 - check changes in Docker environment
 - skip generating dist folder if it already exists.

**Comment by grzegorz-czajkowski** [comment]
All patches merged. Issue can be closed.
