### ISSUE TITLE
error after running ./launch script

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [Samsung/WATT#3]
After running launch script, I could see below error,
any troubleshooting ?

Install nodejs dependencies in .
Install nodejs dependencies in libs/brackets-server/brackets-src
/bin/sh: 1: cd: can't cd to libs/brackets-server/brackets-src
Install nodejs dependencies in libs/brackets-server/brackets-src/src/LiveDevelopment/MultiBrowserImpl/transports/node
/bin/sh: 1: cd: can't cd to libs/brackets-server/brackets-src/src/LiveDevelopment/MultiBrowserImpl/transports/node
Install nodejs dependencies in libs/brackets-server

> brackets@0.5.8 postinstall /home/hyuki/git/public/watt/libs/brackets-server
> node lib/post-install.js

Install nodejs dependencies in libs/brackets-server/embedded-ext/project/node
npm WARN project@1.0.0 No repository field.
Install nodejs dependencies in libs/brackets-server/embedded-ext/importfile/node
npm WARN import@1.0.0 No description
npm WARN import@1.0.0 No repository field.
npm WARN import@1.0.0 No license field.
Install nodejs dependencies in libs/brackets-server/embedded-ext/tizen-profile/node
npm WARN tizen-profile-node@0.0.1 No repository field.
Check mongodb service
mongodb service is started already.
Check emscripten
Use emscripten at /home/hyuki/git/public/watt/tools/emsdk/emscripten/1.37.16
Build if necessary.
Loading "Gruntfile.js" tasks...ERROR
>> Error: ENOENT: no such file or directory, scandir '/home/hyuki/git/public/watt/libs/brackets-server/brackets-src/src/extensions/default'
Warning: Task "build" not found. Use --force to continue.

**Comment by HunseopJeong** [comment]
I added missing brackets submodule #4

**Comment by HunseopJeong** [comment]
Fixed issue by #4
