### ISSUE TITLE
eslint error on apiviewer,

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [Samsung/WATT#44]
/home/hyuki/git/public/watt_up/libs/brackets-server/embedded-ext/apiviewer/main.js
   78:46  error    Missing semicolon                               semi
   80:64  error    Missing semicolon                               semi
   87:45  error    Expected { after 'if' condition                 curly
   91:45  error    Expected { after 'if' condition                 curly
   93:1   warning  Expected indentation of 48 spaces but found 44  indent
   96:45  error    Expected { after 'if' condition                 curly
   97:1   warning  Expected indentation of 48 spaces but found 49  indent
  101:37  error    Expected { after 'else'                         curly
  104:51  error    Missing semicolon                               semi
  106:47  error    Missing semicolon                               semi
  108:43  error    Missing semicolon                               semi
  170:13  error    'fillApis' is not defined                       no-undef

**Comment by Kwanghyuk-Kim** [comment]
@ws29jung 
could you take care of this ?
any missing patch might be there ?

**Comment by HunseopJeong** [comment]
@Kwanghyuk-Kim,
This issue was resolved on the internal source.

@ws29jung,
Could you upload patch to fix it?

**Comment by ws29jung** [comment]
Done with #51 and its merged.
