### ISSUE TITLE
need to add architecture view and WATT demo video

### ISSUE THREAD

**Issue by Kwanghyuk-Kim** [Samsung/WATT#8]
need to add architecture view and WATT demo video to wiki page.

**Comment by Kwanghyuk-Kim** [comment]
Architecture view is added, but demo video is not prepared yet.
https://github.com/Samsung/WATT/wiki/Architecture

**Comment by ws29jung** [comment]
Demo Video is uploaded.
However, github wiki(Markdown) does not allow to play video on the page.
So click thumbnail will take user to the Youtube Video page.

**Comment by Kwanghyuk-Kim** [comment]
LGTM,
